import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { parseGame } from '../src/chess/game'
import { releaseServer } from './helpers/releases'

test('legacy recovery, safe activation, explicit reload, and normal refresh load new builds', async ({ context, page }) => {
  const server = await releaseServer()
  const versionB = 'bbbbbbbbbbbbbbbb'
  const versionC = 'cccccccccccccccc'
  const cachePrefix = `flores-badger:${server.url}:`
  const legacyCache = `badger-flores:${server.url}:${server.initialVersion}`
  try {
    await page.goto(server.url)
    await expect(page.locator('.offline-status')).toContainText('Available offline')
    await page.getByRole('button', { name: 'Import a game' }).click()
    await page.getByRole('textbox', { name: 'Your game in PGN format' }).fill('[White "Saved student"]\n\n1. f3 e5 2. g4 Qh4# 0-1')
    await page.getByRole('button', { name: 'Review this game' }).click()
    await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
    const oldFen = await page.locator('.chessboard').getAttribute('data-fen')
    const quiet = await context.newPage()
    await quiet.goto(`${server.url}quiet.html`)

    server.publish(versionB)
    const stale = await context.newPage()
    await stale.goto(`${server.url}?cacheBust=still-cached`)
    await expect(stale.locator('meta[name="app-build"]')).toHaveAttribute('content', server.initialVersion)
    await stale.close()

    const current = await context.newPage()
    await current.goto(`${server.url}refresh.html?refresh=first-upgrade`)
    await expect(current.locator('meta[name="app-build"]')).toHaveAttribute('content', versionB)
    await expect(current.locator('.offline-status')).toContainText('Available offline')
    await expect(page.locator('meta[name="app-build"]')).toHaveAttribute('content', server.initialVersion)
    await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', oldFen!)
    await expect(page.locator('.app-update-dot')).toBeVisible()
    const legacyAsset = await page.evaluate(() => fetch('./legacy-only.txt', { cache: 'no-store' }).then((response) => response.text()))
    expect(legacyAsset).toBe('Retained for an older open tab.')
    expect(await current.evaluate(() => caches.keys())).toContain(legacyCache)
    expect(await current.evaluate(() => caches.keys())).toContain(cachePrefix + versionB)

    await page.getByRole('button', { name: 'The study guide' }).click()
    await expect(page.locator('.reload-warning')).toContainText('resets the in-memory study')
    await page.getByRole('button', { name: 'Check for updates' }).click()
    await expect(page.locator('.app-update-message')).toContainText('newer version')
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Save study PGN' }).click()
    const download = await downloadPromise
    expect(download.suggestedFilename()).toBe('flores-badger-study.pgn')
    expect(parseGame(await readFile((await download.path())!, 'utf8')).moves).toHaveLength(4)
    await page.getByRole('button', { name: 'Reload app', exact: true }).click()
    await expect(page.locator('meta[name="app-build"]')).toHaveAttribute('content', versionB)
    await expect(page.locator('.offline-status')).toContainText('Available offline')
    expect(new URL(page.url()).searchParams.has('refresh')).toBe(true)
    expect(await current.evaluate(() => caches.keys())).toContain(legacyCache)
    await quiet.close()

    await current.goto(server.url)
    await expect(current.locator('.offline-status')).toContainText('Available offline')
    await expect.poll(() => current.evaluate(() => caches.keys())).not.toContain(legacyCache)
    server.publish(versionC)
    await current.reload()
    await expect(current.locator('meta[name="app-build"]')).toHaveAttribute('content', versionC)
    await expect(current.locator('.offline-status')).toContainText('Available offline')
    await expect(page.locator('meta[name="app-build"]')).toHaveAttribute('content', versionB)

    await context.setOffline(true)
    await current.reload()
    await expect(current.locator('meta[name="app-build"]')).toHaveAttribute('content', versionC)
    await expect(current.locator('.offline-status')).toContainText('Available offline')
    await page.close()
    await current.reload()
    await expect(current.locator('.offline-status')).toContainText('Available offline')
    await expect.poll(async () => (await current.evaluate(() => caches.keys())).filter((key) => key.startsWith(cachePrefix) || key === legacyCache)).toEqual([cachePrefix + versionC])
    expect(server.requests.some((url) => url.startsWith('/study/index.html?refresh='))).toBe(true)
    expect(server.requests.some((url) => url.startsWith('/study/build.json?refresh='))).toBe(true)
    expect(server.requests.some((url) => url === `/study/sw.js?build=${versionB}`)).toBe(true)
    await current.close()
  } finally { await server.close() }
})

test('update-check failures stay visible and bot PGN can be saved before a phone refresh', async ({ page }, testInfo) => {
  const server = await releaseServer()
  server.publish(server.initialVersion)
  try {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto(server.url)
    await expect(page.locator('.offline-status')).toContainText('Available offline')
    const fen = await page.locator('.chessboard').getAttribute('data-fen')
    server.failManifest(503)
    await page.getByRole('button', { name: 'About the coach & analysis' }).click()
    await page.getByRole('button', { name: 'Check for updates' }).click()
    await expect(page.locator('.app-update-message')).toContainText('HTTP 503')
    await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', fen!)
    server.failManifest(200)
    await page.getByRole('button', { name: 'Check for updates' }).click()
    await expect(page.locator('.app-update-message')).toContainText('latest published version')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Close study guide' }).click()
    await page.getByRole('tab', { name: 'Play a bot' }).click()
    await page.getByRole('button', { name: 'Oak, Expert', exact: true }).click()
    await page.getByRole('button', { name: 'White', exact: true }).click()
    await page.getByRole('button', { name: 'Start game', exact: true }).click()
    await page.getByRole('gridcell', { name: /^e2,/ }).click()
    await page.getByRole('gridcell', { name: /^e4,/ }).click()
    await page.getByRole('button', { name: 'About the coach & analysis' }).click()
    const pausedFen = await page.locator('.chessboard').getAttribute('data-fen')
    await page.waitForTimeout(1600)
    await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', pausedFen!)
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Save bot game PGN' }).click()
    const download = await downloadPromise
    expect(download.suggestedFilename()).toBe('flores-badger-practice.pgn')
    const savedGame = parseGame(await readFile((await download.path())!, 'utf8'))
    expect(savedGame.headers.Event).toBe('Flores-Badger practice')
    expect(savedGame.headers.Black).toBe('Oak (Expert)')
    expect(savedGame.positions.at(-1)?.fen).toBe(pausedFen)
    await page.getByRole('button', { name: 'Dark', exact: true }).click()
    await page.setViewportSize({ width: 320, height: 568 })
    await page.locator('.app-updates').scrollIntoViewIfNeeded()
    const updateBounds = await page.locator('.app-updates').boundingBox()
    expect(updateBounds!.x).toBeGreaterThanOrEqual(0)
    expect(updateBounds!.x + updateBounds!.width).toBeLessThanOrEqual(320)
    expect((await page.getByRole('button', { name: 'Reload app', exact: true }).boundingBox())!.height).toBeGreaterThanOrEqual(44)
    await page.screenshot({ path: testInfo.outputPath('phone-dark-updates.png') })
    await page.getByRole('button', { name: 'Close study guide' }).click()
    await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '2')
    await page.close()
  } finally { await server.close() }
})

test('an incomplete deployment cannot replace the saved app or reload an active study', async ({ page }) => {
  const server = await releaseServer()
  server.publish(server.initialVersion)
  try {
    await page.goto(server.url)
    await expect(page.locator('.offline-status')).toContainText('Available offline')
    const fen = await page.locator('.chessboard').getAttribute('data-fen')
    server.publish('dddddddddddddddd')
    server.failOfflineSave(true)
    await page.getByRole('button', { name: 'The study guide' }).click()
    await page.getByRole('button', { name: 'Reload app', exact: true }).click()
    await expect(page.locator('.app-update-message')).toContainText('Some app files could not be saved')
    await expect(page.locator('meta[name="app-build"]')).toHaveAttribute('content', server.initialVersion)
    await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', fen!)
    expect(await page.evaluate(() => caches.keys())).toContain(`flores-badger:${server.url}:${server.initialVersion}`)
    server.failOfflineSave(false)
    await page.getByRole('button', { name: 'Reload app', exact: true }).click()
    await expect(page.locator('meta[name="app-build"]')).toHaveAttribute('content', 'dddddddddddddddd')
    await expect(page.locator('.offline-status')).toContainText('Available offline')
    await page.close()
  } finally { await server.close() }
})
