import { expect, test } from '@playwright/test'
import { Chess } from 'chess.js'
import { readFile } from 'node:fs/promises'
import { BOT_LEVELS } from '../src/chess/bots'
import { parseGame } from '../src/chess/game'

test.use({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })

test('all five bot levels make legal replies on a phone, with touch targets and PGN export', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('./')
  await page.getByRole('tab', { name: 'Play a bot' }).tap()
  await expect(page.getByRole('progressbar')).toHaveCount(0)
  for (const [index, bot] of BOT_LEVELS.entries()) {
    if (index) await page.getByRole('button', { name: 'New game', exact: true }).tap()
    await page.getByRole('button', { name: `${bot.name}, ${bot.label}`, exact: true }).tap()
    await page.getByRole('button', { name: 'White', exact: true }).tap()
    await page.getByRole('button', { name: 'Start game', exact: true }).tap()
    const boardBox = await page.locator('.chessboard').boundingBox()
    expect(boardBox!.width).toBeGreaterThanOrEqual(340)
    expect(boardBox!.height).toBeCloseTo(boardBox!.width, 0)
    expect((await page.getByRole('gridcell', { name: /^e2,/ }).boundingBox())!.width).toBeGreaterThanOrEqual(40)
    await page.getByRole('gridcell', { name: /^e2,/ }).tap()
    await expect(page.locator('[data-square="e4"] .legal-dot')).toHaveCount(1)
    await expect(page.getByRole('gridcell', { name: /^e2,/ })).toHaveAttribute('aria-selected', 'true')
    await page.getByRole('gridcell', { name: /^e4,/ }).tap()
    await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '2')
    const fen = await page.locator('.chessboard').getAttribute('data-fen')
    expect(new Chess(fen!).turn()).toBe('w')
    await expect(page.locator('.bot-error')).toHaveCount(0)
  }
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save game PGN' }).tap()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('flores-badger-practice.pgn')
  const pgn = await readFile((await download.path())!, 'utf8')
  const exported = parseGame(pgn)
  expect(exported.headers.Event).toBe('Flores-Badger practice')
  expect(exported.headers.Black).toBe('Oak (Expert)')
  expect(exported.headers.BotSkill).toBe('20')
  expect(exported.positions.at(-1)?.fen).toBe(await page.locator('.chessboard').getAttribute('data-fen'))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const analyzeBox = await page.getByRole('button', { name: 'Analyze the game so far' }).boundingBox()
  expect(analyzeBox!.height).toBeGreaterThanOrEqual(44)
  await page.screenshot({ path: testInfo.outputPath('phone-bot-game.png'), fullPage: true })
  await page.setViewportSize({ width: 320, height: 780 })
  expect((await page.locator('.chessboard').boundingBox())!.width).toBeGreaterThanOrEqual(280)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('takebacks cancel thinking, Black gets the first bot move, and keyboard input stays on the play board', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('tab', { name: 'Play a bot' }).click()
  await page.getByRole('button', { name: 'Sprout, Beginner', exact: true }).click()
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await page.getByRole('gridcell', { name: /^e2,/ }).focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Take back', exact: true }).click()
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '0')
  await page.waitForTimeout(650)
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '0')
  await expect(page.locator('.play-turn-status')).toContainText('Your move')

  await page.getByRole('button', { name: 'New game', exact: true }).click()
  await page.getByRole('button', { name: 'Black', exact: true }).click()
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '1')
  await expect(page.locator('.board-square').first()).toHaveAttribute('data-square', 'h1')
  await expect(page.getByRole('button', { name: 'Take back', exact: true })).toBeDisabled()
  await expect(page.locator('.play-turn-status')).toContainText('Your move')
  await page.getByRole('button', { name: 'Flip playing board' }).click()
  await expect(page.locator('.board-square').first()).toHaveAttribute('data-square', 'a8')
  await expect(page.locator('.bot-error')).toHaveCount(0)
})

test('a completed bot game flows into analysis, survives switching views, and Chess.com import remains available', async ({ page }) => {
  await page.goto('./')
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100', { timeout: 60000 })
  await page.getByRole('tab', { name: 'Play a bot' }).click()
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await page.getByRole('gridcell', { name: /^e2,/ }).click()
  await page.getByRole('gridcell', { name: /^e4,/ }).click()
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '2')
  const playedFen = await page.locator('.chessboard').getAttribute('data-fen')
  await page.getByRole('tab', { name: 'Review a game' }).click()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  await expect(page.locator('.status-copy')).toContainText('Reviewed')
  await page.getByRole('tab', { name: 'Play a bot' }).click()
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', playedFen!)
  await page.getByRole('button', { name: 'Resign', exact: true }).click()
  await page.getByRole('button', { name: 'Resign game', exact: true }).click()
  await expect(page.locator('.play-turn-status')).toContainText('Black wins by resignation')
  await page.getByRole('button', { name: 'Analyze this game', exact: true }).click()
  await expect(page.getByRole('tab', { name: 'Review a game' })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Moves', exact: true }).click()
  await expect(page.locator('.move-cell')).toHaveCount(2)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  await expect(page.locator('.game-result')).toContainText('0-1')

  await page.getByRole('button', { name: 'Import a game' }).click()
  await page.getByRole('textbox', { name: 'Your game in PGN format' }).fill('[Event "Live Chess"]\n[Site "Chess.com"]\n[White "Phone student"]\n[Black "Club friend"]\n[Result "*"]\n\n1. e4 {[%clk 0:10:00]} e5 2. Nf3 Nc6 3. Bc4 Nf6 *')
  await page.getByRole('button', { name: 'Review this game' }).click()
  await page.getByRole('tab', { name: 'Moves', exact: true }).click()
  await expect(page.locator('.move-cell')).toHaveCount(6)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  await page.getByRole('tab', { name: 'Chart', exact: true }).click()
  await expect(page.locator('.player-info')).toContainText(['Phone student', 'Club friend'])
  await page.getByRole('tab', { name: 'Play a bot' }).click()
  await expect(page.locator('.play-turn-status')).toContainText('Black wins by resignation')
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', playedFen!)
})

test('a fresh offline page can play a bot and analyze that new game without network access', async ({ page, context }) => {
  const failed: string[] = []
  await page.goto('./')
  await expect(page.locator('.offline-status')).toContainText('Available offline')
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  await context.setOffline(true)
  page.on('requestfailed', (request) => failed.push(request.url()))
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.getByRole('tab', { name: 'Play a bot' }).tap()
  await page.getByRole('button', { name: 'Fern, Club', exact: true }).tap()
  await page.getByRole('button', { name: 'Black', exact: true }).tap()
  await page.getByRole('button', { name: 'Start game', exact: true }).tap()
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '1')
  const board = new Chess((await page.locator('.chessboard').getAttribute('data-fen'))!)
  const move = board.moves({ verbose: true })[0]
  await page.locator(`[data-square="${move.from}"]`).tap()
  await page.locator(`[data-square="${move.to}"]`).tap()
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '3')
  await page.getByRole('button', { name: 'Analyze the game so far' }).tap()
  await page.getByRole('tab', { name: 'Moves', exact: true }).tap()
  await expect(page.locator('.move-cell')).toHaveCount(3)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  await expect(page.locator('.engine-error, .offline-warning')).toHaveCount(0)
  expect(failed).toEqual([])
})

test('a failed bot can retry without losing or inventing moves', async ({ page, context }) => {
  await context.route('**/engine/**', (route) => route.abort())
  await page.goto('./')
  await page.getByRole('tab', { name: 'Play a bot' }).click()
  await page.getByRole('button', { name: 'Black', exact: true }).click()
  await page.getByRole('button', { name: 'Start game', exact: true }).click()
  await expect(page.locator('.bot-error')).toContainText('Your game is safe here', { timeout: 40000 })
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '0')
  await context.unroute('**/engine/**')
  await page.getByRole('button', { name: 'Retry bot' }).click()
  await expect(page.locator('.practice-moves')).toHaveAttribute('data-ply-count', '1')
  await expect(page.locator('.bot-error')).toHaveCount(0)
  await expect(page.locator('.play-turn-status')).toContainText('Your move')
})
