import { expect, test } from '@playwright/test'
import { Chess } from 'chess.js'
import { readFile } from 'node:fs/promises'
import { DEMO_PGN, parseGame } from '../src/chess/game'
import { showPlayedPosition } from './helpers/review'

test('real local analysis, legal alternatives, key moments, playback and export work under a subpath', async ({ page }, testInfo) => {
  const errors: string[] = []
  const requests: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('request', (request) => requests.push(request.url()))
  await page.goto('./')
  await showPlayedPosition(page)
  await expect(page.getByRole('heading', { name: 'Good games teach. Every game can.' })).toBeVisible()
  await expect(page.getByRole('progressbar', { name: 'Game analysis progress' })).toHaveAttribute('aria-valuenow', '100', { timeout: 60000 })
  await expect(page.locator('.engine-error')).toHaveCount(0)
  await expect(page.locator('.move-cell .grade-badge')).toHaveCount(33)
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', parseGame(DEMO_PGN).moves[17].after)
  await page.screenshot({ path: testInfo.outputPath('desktop-review.png'), fullPage: true })

  const bestButton = page.getByRole('button', { name: /^Explore best alternative/ })
  const bestSan = (await bestButton.getAttribute('aria-label'))!.replace('Explore best alternative ', '')
  await bestButton.click()
  const before = parseGame(DEMO_PGN).moves[17].before
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', before)
  await expect(page.locator('.board-arrows path[marker-end]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Next move', exact: true }).click()
  const alternative = new Chess(before)
  alternative.move(bestSan)
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', alternative.fen())
  await expect(page.locator('.variation-step-explanation')).toContainText(`Black plays ${bestSan}`)
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('.board-caption')).toContainText('2 /')
  await page.getByRole('button', { name: 'Previous move', exact: true }).click()
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', alternative.fen())
  await page.getByRole('button', { name: 'Flip board' }).click()
  await expect(page.locator('.board-square').first()).toHaveAttribute('data-square', 'h1')
  await page.keyboard.press('f')
  await expect(page.locator('.board-square').first()).toHaveAttribute('data-square', 'a8')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Back to game', exact: true })).toHaveCount(0)
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', parseGame(DEMO_PGN).moves[17].after)

  await page.getByRole('button', { name: 'First position' }).click()
  await page.getByRole('button', { name: 'Next key moment', exact: true }).click()
  await expect(page.locator('.move-selected .grade-badge')).toHaveCount(1)
  await expect(page.locator('.move-selected .grade-badge')).not.toHaveClass(/grade-(book|good|excellent|best)/)
  await page.getByRole('button', { name: 'Play moves', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause playback', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pause playback', exact: true }).click()
  await page.getByRole('slider', { name: 'Navigate the game timeline' }).focus()
  await page.keyboard.press('End')
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', parseGame(DEMO_PGN).positions[33].fen)
  await expect(page.locator('.board-caption')).toContainText('White wins by checkmate')
  await expect(page.locator('.square-check')).toHaveCount(1)
  await page.getByRole('tab', { name: 'Insights' }).click()
  await expect(page.locator('.classification-counts > div')).toHaveCount(10)

  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export study' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('flores-badger-study.pgn')
  const exported = await readFile((await download.path())!, 'utf8')
  expect(exported).toContain('[%eval')
  expect(parseGame(exported).headers.Annotator).toBe('Flores-Badger / Stockfish 17.1 lite')
  expect(parseGame(exported).moves.map((move) => move.uci)).toEqual(parseGame(DEMO_PGN).moves.map((move) => move.uci))
  expect(requests.some((url) => url.endsWith('.wasm'))).toBe(true)
  expect(requests.every((url) => new URL(url).hostname === '127.0.0.1')).toBe(true)
  expect(errors).toEqual([])
})

test('import validation, replacement during search, Black-first FEN, and promotion are handled', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Import a game' }).click()
  const textbox = page.getByRole('textbox', { name: 'Your game in PGN format' })
  await textbox.fill('1. e4 e5 2. Bh6')
  await page.getByRole('button', { name: 'Review this game' }).click()
  await expect(page.getByRole('alert')).toContainText("couldn't read this game")
  await textbox.fill('[SetUp "1"]\n[FEN "4k3/8/8/8/8/8/8/R3K3 b Q - 0 17"]\n[White "Local student"]\n\n17... Kf7 18. O-O-O *')
  await page.getByRole('button', { name: 'Review this game' }).click()
  await showPlayedPosition(page)
  await expect(page.getByRole('dialog', { name: 'Every game has something to teach.' })).not.toBeVisible()
  await expect(page.locator('.board-caption')).toContainText('17... Kf7')
  await expect(page.locator('.move-cell')).toHaveCount(2)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  await page.getByRole('button', { name: 'Next move', exact: true }).click()
  await expect(page.locator('[data-square="c1"] .chess-piece')).toHaveCount(1)
  await expect(page.locator('[data-square="d1"] .chess-piece')).toHaveCount(1)
  await expect(page.locator('.engine-error')).toHaveCount(0)

  await page.getByRole('button', { name: 'Import a game' }).click()
  await textbox.fill('[SetUp "1"]\n[FEN "7k/P7/8/8/8/8/8/7K w - - 0 1"]\n\n1. a8=N *')
  await page.getByRole('button', { name: 'Review this game' }).click()
  await showPlayedPosition(page)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  await expect(page.locator('.board-caption')).toContainText('insufficient material')
  await expect(page.locator('.chessboard')).toHaveAttribute('data-fen', /N6k/)
  await page.getByRole('button', { name: 'Restart analysis' }).click()
  await page.getByRole('button', { name: 'Stop analysis' }).click()
  await expect(page.locator('.status-copy')).toContainText('paused')
  await page.waitForTimeout(600)
  await expect(page.locator('.status-copy')).toContainText('paused')
})

test('engine failures stay visible, can be retried, and the mobile layout stays usable', async ({ page, context }, testInfo) => {
  await context.route('**/engine/**', (route) => route.abort())
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./')
  await expect(page.locator('.engine-error')).toBeVisible({ timeout: 40000 })
  await expect(page.locator('.engine-error')).toContainText('board and PGN navigation still work')
  await page.getByRole('button', { name: 'Next move', exact: true }).click()
  await expect(page.locator('.board-caption')).toContainText('10. Nxb5')
  await context.unroute('**/engine/**')
  await page.getByRole('button', { name: 'Retry analysis' }).click()
  await expect(page.locator('.engine-error')).toHaveCount(0)
  await expect(page.locator('.offline-warning')).toBeVisible()
  await page.getByRole('button', { name: 'Retry offline saving' }).click()
  await expect(page.locator('.offline-status')).toContainText('Available offline')
  await page.getByRole('button', { name: 'Import a game' }).click()
  await page.getByRole('textbox', { name: 'Your game in PGN format' }).fill('1. f3 e5 2. g4 Qh4# 0-1')
  await page.getByRole('button', { name: 'Review this game' }).click()
  await showPlayedPosition(page)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  await page.getByRole('button', { name: 'Last position' }).click()
  await expect(page.locator('.board-caption')).toContainText('Black wins by checkmate')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mobile-review.png'), fullPage: true })
  await page.getByRole('button', { name: 'About the coach & analysis' }).click()
  await expect(page.getByRole('heading', { name: 'Understanding your study companion.' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Understanding your study companion.' })).not.toBeVisible()
})

test('the entire app reloads and analyzes a new game with all network access disabled', async ({ page, context }) => {
  const errors: string[] = []
  const failed: string[] = []
  let cachedEngineResponse = false
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('./')
  await expect(page.locator('.offline-status')).toContainText('Available offline', { timeout: 60000 })
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  await expect(page.locator('meta[http-equiv="Content-Security-Policy"]')).toHaveAttribute('content', /connect-src 'self'/)

  page.on('requestfailed', (request) => failed.push(request.url()))
  page.on('response', (response) => {
    if (response.url().endsWith('.wasm') && response.fromServiceWorker()) cachedEngineResponse = true
  })
  await context.setOffline(true)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.locator('.offline-status')).toContainText('Available offline')
  await page.getByRole('button', { name: 'Import a game' }).click()
  await page.getByRole('textbox', { name: 'Your game in PGN format' }).fill('[White "Offline student"]\n[Black "Local engine"]\n\n1. f3 e5 2. g4 Qh4# 0-1')
  await page.getByRole('button', { name: 'Review this game' }).click()
  await showPlayedPosition(page)
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100', { timeout: 60000 })
  await page.getByLabel('Review depth').selectOption('deep')
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100', { timeout: 60000 })
  await page.getByRole('button', { name: 'Last position' }).click()
  await expect(page.locator('.board-caption')).toContainText('Black wins by checkmate')
  await expect(page.locator('.engine-error, .offline-warning')).toHaveCount(0)
  await page.getByRole('button', { name: /^Explore best alternative/ }).click()
  await page.getByRole('button', { name: 'Next move', exact: true }).click()
  await expect(page.locator('.variation-step-explanation')).toContainText('Black plays Qh4#')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export study' }).click()
  const download = await downloadPromise
  expect(await readFile((await download.path())!, 'utf8')).toContain('[%eval')
  expect(cachedEngineResponse).toBe(true)
  expect(failed).toEqual([])
  expect(errors).toEqual([])
})
